
import Head from "next/head";
import Image from "next/image";
import Main from "../components/Main";
import Navbar from "../components/Navbar";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import NavPic from '../public/assets/nb-logo-png-transparent.png'


export default function Home() {
  return (
    <div>
      <Head>
        
        <title>Norbert Baster | Front-end Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <Image src={NavPic} alt="nav-pic"/>
      </Head>
      <Navbar />
      <Main />
      <About/>
      <Skills/>
      <Projects/>
    </div>
  );
}